# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65242c87c305f71c4a85d805d551e088296f662c8385f8c7e8d82b19ab69b345fb3d17f022a411550914e1fd2dc9ddf56c315c5e0adc60cb16635e7c42e90e3f

test:
  secret_key_base: d6b274d9309c8f9c62d031475c9e0ceda9b1382c4602c63c0c147b66b1da11974460ca0fea6382226ac0076728a245cdd6ff824d9d84b094ba1cee372294b2b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
